//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HandIn4Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppartmentcharacteristicSet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AppartmentcharacteristicSet()
        {
            this.ReadingSets = new HashSet<ReadingSet>();
            this.SensorcharacteristicSets = new HashSet<SensorcharacteristicSet>();
        }
    
        public int appartmentId { get; set; }
        public int No { get; set; }
        public double Size { get; set; }
        public int Floor { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReadingSet> ReadingSets { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SensorcharacteristicSet> SensorcharacteristicSets { get; set; }
    }
}
