//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HandIn4Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReadingSet
    {
        public int Id { get; set; }
        public double value { get; set; }
        public System.DateTime timestamp { get; set; }
        public int SensorID { get; set; }
        public int appartmentId { get; set; }
    
        public virtual AppartmentcharacteristicSet AppartmentcharacteristicSet { get; set; }
        public virtual SensorcharacteristicSet SensorcharacteristicSet { get; set; }
    }
}
